services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_MYSQL_LOCALHOST_USER: true
    secrets:
      - db_password
    expose:
      - ${DB_PORT}
    volumes:
      - mysql:/var/lib/mysql:rw,Z
    networks:
      - privacyidea
    restart: always
    profiles:
      - fullstack
      - stack
      - radius
      - openldap

  privacyidea:
    image: privacyidea-docker:${PI_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      PI_BOOTSTRAP: ${PI_BOOTSTRAP:-false}
      PI_UPDATE: ${PI_UPDATE:-false}
      PI_ADMIN: admin
      DB_PASSWORD: /run/secrets/db_password
      PI_PASSWORD: /run/secrets/pi_admin_pass
      PI_SECRET: /run/secrets/pi_secret
      PI_PEPPER: /run/secrets/pi_pepper
    env_file:
      - ${ENVIRONMENT}
    secrets:
      - db_password
      - pi_admin_pass
      - pi_secret
      - pi_pepper
    expose:
      - ${PI_PORT}
    volumes:
      - pilog:/var/log/privacyidea:rw,Z
      - piconfig:/etc/privacyidea:rw,Z
      - type: bind
        source: scripts/
        target: /etc/privacyidea/scripts/
        read_only: true
      - type: bind
        source: templates/resolver.json
        target: /etc/privacyidea/resolver.json
        read_only: true
    networks:
      - privacyidea
    healthcheck:
        test: [ "CMD", "/opt/privacyidea/healthcheck.py" ]
        start_period: 10s
        start_interval: 10s
        interval: 12s
        timeout: 5s
        retries: 3
    restart: always
    profiles:
      - fullstack
      - stack
      - radius
      - openldap

  reverse_proxy:
    image: nginx:stable-alpine
    environment:
      APP_PORT: ${PI_PORT}
      SERVERNAME: ${PROXY_SERVERNAME:-localhost}
    ports:
      - "${PROXY_PORT}:443"
    volumes:
      - type: bind
        source: ./templates/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./ssl/pi.key
        target: /etc/nginx/ssl/pi.key
        read_only: true
      - type: bind
        source: ./ssl/pi.pem
        target: /etc/nginx/ssl/pi.pem
        read_only: true
      - type: bind
        source: ./templates/nginx_default.conf.template
        target: /etc/nginx/templates/default.conf.template
        read_only: true
    networks:
      - privacyidea
    restart: always
    profiles:
      - fullstack
      - stack
      - radius
      - openldap

  freeradius:
    image: gpappsoft/privacyidea-freeradius:latest
    environment:
      RADIUS_PI_HOST: reverse_proxy
    ports:
      - "${RADIUS_PORT:-1812}:1812/tcp"
      - "${RADIUS_PORT:-1812}:1812/udp"
      - "${RADIUS_PORT_INC:-1813}:1813/udp"
    command:
      # uncomment the two lines below to debug radius
      #- freeradius
      #- -X
    volumes:
      - type: bind
        source: ./templates/clients.conf
        target: /etc/raddb/clients.conf
        read_only: true
    networks:
      - privacyidea
    restart: always
    profiles:
      - fullstack
      - radius

  openldap:
    image: osixia/openldap:latest
    environment:
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_LOG_LEVEL: "0"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ADMIN_PASSWORD: "openldap"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_SEED_INTERNAL_LDIF_PATH: /ldif
      LDAP_RFC2307BIS_SCHEMA: "true"
    tty: true
    stdin_open: true
    ports:
      - "${LDAP_PORT}:389"
    networks:
      - privacyidea
    volumes:
      - type: bind
        source: ./templates/sample.ldif
        target: /ldif/sample.ldif
        read_only: true
    restart: always
    profiles:
      - fullstack
      - ldap
    
secrets:
  db_password:
    file: secrets/db_password
  pi_secret:
    file: secrets/pi_secret
  pi_pepper:
    file: secrets/pi_pepper
  pi_admin_pass:
     file: secrets/pi_admin_pass

volumes:
  pilog: {}
  piconfig: {}
  mysql: {}
 
networks:
  privacyidea: {}

