apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: privacyidea-ci
  annotations:
    tekton.dev/docker-0: https://ghcr.io
type: kubernetes.io/basic-auth
stringData:
  username: REPLACE_WITH_GITHUB_USERNAME
  password: REPLACE_WITH_GITHUB_PAT_WITH_PACKAGES_WRITE
