apiVersion: v1
kind: Secret
metadata:
  name: github-auth
  namespace: privacyidea-ci
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: REPLACE_WITH_GITHUB_USERNAME
  password: REPLACE_WITH_GITHUB_PAT_WITH_REPO_READ
